<a href="https://colab.research.google.com/github/SurajGusain0007/Numpy/blob/main/Creating_arrays_and_Dimension.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Now we will create a numpy  ndarray object
#the array object in numpy is call ndarry
#array()

In [3]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#We can also pass a list,tuple or any array like object and it will be converted to ndarray
y=np.array((1,2,3,4,5))
print(y)
print((type(y)))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#Dimensions in array
# A dimensions in Array is one level of array depth(nested array)
#0-D-Scalars ,are the elements in an array,each value in an array is a 0-d array
# Now we will create 0-D array with 42
x=np.array(42)
print(x)
print(type(x))

42
<class 'numpy.ndarray'>


In [7]:
#1-d array-an array that has 0-d array as its elements is called 1-d array
#or collection of 0-d array also called 1-D array
y=np.array([1,2,3,4,5])
print(y)


[1 2 3 4 5]


In [8]:
#2-d array
z=np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(z)
print(type(z))

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
<class 'numpy.ndarray'>


In [9]:
# we will create a 3-D array with two 2-D array3-d array or collection of 2-d array
x=np.array([[[1,2,3,4],[5,6,7,8]],
           [[11,12,13,14],[15,16,17,18]]])
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]


In [10]:
# Check how many dimensions the array have
a=np.array(12)
b=np.array([1,2,3,4])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3,4],[5,6,7,8]]
            ,[[11,12,13,14],[15,16,17,18]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
#create an array with 5 dim and verify that it has
x=np.array([1,2,3,4,5],ndmin=5)
print(x)
print("No of dimension",x.ndim)

[[[[[1 2 3 4 5]]]]]
No of dimension 5


In [12]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=5)
print(x)
print("No of dimension",x.ndim)

[[[[[ 1  2  3  4  5]
    [ 6  7  8  9 10]]]]]
No of dimension 5
