<a href="https://colab.research.google.com/github/SurajGusain0007/Numpy/blob/main/Numpy_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#Splitting arrays in numpy
#array_split()
#split the array in 3 parts
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,3)
print(y)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# Split into 4 parts
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,4)
print(y)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
#Split into array
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,3)
print(y[0])
print(y[1])
print(y[2])

[1 2]
[3 4]
[5 6]


In [ ]:
#Splitting the 2-d array
x=np.array([[1,2],[4,5],[6,7],[8,9],[10,11]] )
y=np.array_split(x,3)
print(y)

[array([[1, 2],
       [4, 5]]), array([[6, 7],
       [8, 9]]), array([[10, 11]])]


In [ ]:
#splittting the 2-D into three 2-D along with axis
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y=np.array_split(x,3)
print(y)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15]])]


In [ ]:
#Array Searching--you can search an array for a certain value and return the indexes that get the match
#where()
x=np.array([1,2,3,4,5,4,7,7])
y=np.where(x==4)
print(y)


(array([3, 5]),)


In [ ]:
#Now we will find the indexes where the values are even
x=np.array([1,2,3,4,5,4,7,7])
y=np.where(x%2==0)
print(y)

(array([1, 3, 5]),)


In [ ]:
#Searchsorted:Perform Binary search in array
#we will now find the index where the value 7 should be insterted.
x=np.array([6,7,8,9])
y=np.searchsorted(x,7)
print(y)


1


In [ ]:
#Now we will search from right side
x=np.array([6,7,8,9])
y=np.searchsorted(x,7,side='right')
print(y)


2


In [ ]:
#How to search multiple value
x=np.array([6,7,8,9])
y=np.searchsorted(x,[2,4,11])
print(y)


[0 0 4]


In [ ]:
#Numpy sorting array
#sort()--the numpy ndarray object has a function which is called sort() and this will sort a specified array

x=np.array([11,3,4,2,5])
print(np.sort(x))

[ 2  3  4  5 11]


In [ ]:
#sort the array alphabatically
x=np.array(['banana','apple','grapes'])
print(np.sort(x))

['apple' 'banana' 'grapes']


In [ ]:
#sorting 2-d array
x=np.array([[4,3,2],[23,12,11]])
print(np.sort(x))

[[ 2  3  4]
 [11 12 23]]


In [ ]:
# Getting some elements out of an existing array and creating a new array is called filterting
# A boolean index list is a list of boolean corresponding of index t or f

x=np.array([12,13,14,15])
y=[True,False,True,False]
z=x[y]
print(z)

[12 14]


In [ ]:
# Now we will create a filter array
x=np.array([1,2,3,4])
y=[]
for i in x:
  if i>2:
    y.append(True)
  else:
    y.append(False)
z=x[y]
print(y)
print(z)

[False, False, True, True]
[3 4]


In [ ]:
# Random meaning - something that cannot be predicted logically.
# Now we will generate a random number from 0 to 100
from numpy import random 
sharad = random.randint(100)
print(sharad) 

# You can also genetrate float() via rand() from 0 to 1
from numpy import random 
sharad = random.rand()
print(sharad) 

# You can also generate random Array.
# we will generate a 1-D array containing 5 random int from 0 to 100:
from numpy import random 
sharad = random.randint(100, size=(5))
print(sharad) 

# You can also generate random Array.
# we will generate a 2-D array with 3 rows, each row  containing 5 random int from 0 to 100:
from numpy import random 
sharad = random.randint(100, size=(3, 5))
print(sharad) 

# You can also generate random Array.
# we will generate a 1-D array containing 5 random float:
from numpy import random 
sharad = random.rand(5)
print(sharad) 

# You can also generate random Array.
# we will generate a 2-D array with 3 rows, each containing 5 random float:
from numpy import random 
sharad = random.rand(3, 5)
print(sharad) 

# you can also generate random numbers from an array
# choice()

from numpy import random 
sharad = random.choice([3,5,7,9,1,4,6])
print(sharad) 

# you can also generate random numbers from an 2-D array
# choice()

from numpy import random 
sharad = random.choice([3,5,7,9,1,4,6], size=(3, 5))
print(sharad) 

63
0.9642799631473536
[61 47 22 32 76]
[[27 74 22 59 92]
 [66 29 32 61 93]
 [26 74 69 65 89]]
[0.36885013 0.92856623 0.52668095 0.69816996 0.65393192]
[[0.20437323 0.44634349 0.07984244 0.42729429 0.7011156 ]
 [0.56226889 0.7182829  0.05141823 0.35233695 0.73165041]
 [0.38430593 0.06127199 0.30185542 0.17256573 0.43082351]]
9
[[4 9 3 6 7]
 [6 1 5 1 4]
 [1 7 5 5 6]]


In [ ]:
#Random Distributions
# Data distributions is a list of all possible value and how often each value error.
#Such list are important when working with statistics and data science
#Random distributions:probability distributions

#now we will generate 1-d with 100 values where each value has to be 3,5,7,9
# the probability for the value 3 is set to be 0.1

# the probability for the value 3 is set to be 0.3

# the probability for the value 3 is set to be 0.6

# the probability for the value 3 is set to be 0.

# the sum of all probability numbers should be 1

from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)


[7 5 7 5 5 7 7 7 3 7 7 5 7 5 3 7 7 7 5 7 7 7 7 7 7 5 5 7 7 7 5 3 7 7 7 5 7
 7 7 5 7 5 7 7 7 7 5 7 7 7 7 7 7 7 7 7 7 7 7 5 5 7 3 5 7 7 7 3 5 5 7 3 7 5
 5 7 7 5 7 5 7 7 7 5 7 5 7 7 7 5 5 7 7 5 7 5 5 7 5 3]


In [ ]:
#now we will return 2-d with 3 rows each containing 5 values
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(3,5))
print(x)


[[7 7 7 5 7]
 [7 3 7 5 7]
 [7 7 7 5 7]]


In [ ]:
# Permutation refers to an arrangement of elements like [3,2,1] is permutation of [1,2,3] and vice versa.
# the numpy random module provides 2 methods: shuffle() and permutation().

# shuffle() method make changes to the original array 
# now we will randomly suffle elemements for the below array:
from numpy import random
import numpy as np
sharad = np.array([1,2,3,4,5])
random.shuffle(sharad)
print(sharad)

# now we will generate a permutation of elements for the below array:
# the permutation() method leaves the original array unchanged.
from numpy import random
import numpy as np
sharad = np.array([1,2,3,4,5])
print(random.permutation(sharad)) 
 

[3 5 1 4 2]
[3 5 1 2 4]


In [ ]:
# arithemtic operators: +, -, / , *
# by using ufunc additional arguments like, where, dtype and out.
# here now we will use add()
import numpy as np
sharad1 = np.array([10,11,12,13,14,15])
sharad2 = np.array([20,21,22,23,24,25])
sharadnew = np.add(sharad1, sharad2)
print(sharadnew)

#  example of substracting the value
import numpy as np
sharad1 = np.array([10,11,12,13,14,15])
sharad2 = np.array([20,21,22,23,24,25])
sharadnew = np.subtract(sharad1, sharad2)
print(sharadnew)

# example of multipication
import numpy as np
sharad1 = np.array([10,11,12,13,14,15])
sharad2 = np.array([20,21,22,23,24,25])
sharadnew = np.multiply(sharad1, sharad2)
print(sharadnew)

# example of divide()
import numpy as np
sharad1 = np.array([10,11,12,13,14,15])
sharad2 = np.array([20,21,22,23,24,25])
sharadnew = np.divide(sharad1, sharad2)
print(sharadnew)

# power() function raises the value from the 1st array to the power of the values of the 2nd array and return the results in a new array.

import numpy as np
sharad1 = np.array([10,20,30,40,50,60])
sharad2 = np.array([3,5,6,8,2,33])
sharadnew = np.power(sharad1, sharad2)
print(sharadnew)

# reminder- mod() and reminder() fucntions return the reminder of the 1st array corrosponding to the 2nd array, and result in the new array.
import numpy as np
sharad1 = np.array([10,20,30,40,50,60])
sharad2 = np.array([3,7,9,8,2,33])
sharadnew = np.mod(sharad1, sharad2)
print(sharadnew)

# by using reminder()
import numpy as np
sharad1 = np.array([10,20,30,40,50,60])
sharad2 = np.array([3,7,9,8,2,33])
sharadnew = np.remainder(sharad1, sharad2)
print(sharadnew)

# quotient and mod(reminder)
# the divmod() function return both the quotient and mod.
import numpy as np
sharad1 = np.array([10,20,30,40,50,60])
sharad2 = np.array([3,7,9,8,2,33])
sharadnew = np.divmod(sharad1, sharad2)
print(sharadnew)

# absolute() and abs()- do the same operation but here we should use absolute() to avoid confusion with python inbuilt function math.abs().
import numpy as np
sharad = np.array([-1,-2,-3,-4,-5])
sharadnew = np.absolute(sharad)
print(sharadnew) 


[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[         1000       3200000     729000000 6553600000000          2500
             0]
[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]
(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))
[1 2 3 4 5]


In [ ]:
# rounding decimals: there are 5 ways of rounding off the decimals in numpy: truncation, fix, rounding, floor, ceil.

# truncation: trunc() and fix()
# here we are truncating the below array, these command remove the decimals and return the float number closest to zero.
import numpy as np
sharad = np.trunc([-3.1666, 3.6667])
print(sharad)

# fix() example
import numpy as np
sharad = np.fix([-3.1666, 3.6667])
print(sharad)

# rounding: the around() function increments preceding digit or decimal by nearest to 1: if n>5 =1 or n<5 =0.
import numpy as np
sharad = np.around(3.1666, 2)
print(sharad)

# floor() - round off decimals to the lower integer.
import numpy as np
sharad = np.floor([-3.1666, 3.6667])
print(sharad)

# ceil(): round off decimals to the upper integer.
import numpy as np
sharad = np.ceil([-3.1666, 3.6667])
print(sharad)

[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


In [ ]:
# summations: difference: addition is done between 2 arguments whereas summation happens over n elements.

# adding the 2 array.
import numpy as np
sharad1 = np.array([1,2,3])
sharad2 = np.array([1,2,3])
sharadnew = np.add(sharad1, sharad2)
print(sharadnew)

# sum the values in 2 array:
import numpy as np
sharad1 = np.array([1,2,3])
sharad2 = np.array([1,2,3])
sharadnew = np.sum([sharad1, sharad2])
print(sharadnew)

# summation over an axis: if you specify axis=1, numpy will sum the number in each array.

import numpy as np
sharad1 = np.array([1,2,3])
sharad2 = np.array([1,2,3])
sharadnew = np.sum([sharad1, sharad2], axis=1)
print(sharadnew)

# cummulative sum: means partially adding thr element in array.
# example: [1,2,3,4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1,3,6,10] represent by cumsum()
import numpy as np
sharad = np.array([1,2,3])
sharadnew = np.cumsum(sharad)
print(sharadnew)

[2 4 6]
12
[6 6]
[1 3 6]


In [ ]:
# products: use prod() function.
# here we will find the product of the element of the below array:
import numpy as np
sharad = np.array([1,2,3,4]) # 1*2*3*4 = 24
sharadnew = np.prod(sharad)
print(sharadnew)

# here we will find the product of elemets in 2 different array:
import numpy as np
sharad1 = np.array([1,2,3,4])
sharad2 = np.array([5,6,7,8])
sharadnew = np.prod([sharad1, sharad2]) # 1*2*3*4*5*6*7*8 = 40320
print(sharadnew)

# product over an axis
import numpy as np
sharad1 = np.array([1,2,3,4])
sharad2 = np.array([5,6,7,8])
sharadnew = np.prod([sharad1, sharad2], axis=1) 
print(sharadnew)

# cummulative product:
# example  the partial product of [1,2,3,4] is [1,1*2,1*2*3,1*2*3*4] = [1,2,6,24] represented by cumprod().
import numpy as np
sharad = np.array([5,6,7,8])
sharadnew = np.cumprod(sharad)
print(sharadnew)

24
40320
[  24 1680]
[   5   30  210 1680]


In [ ]:
# difference: use diff() function for finding the difference
# example: [1,2,3,4],  the deiscreate difference of this would be [2-1, 3-2, 4-3] = [1,1,1] by using diff()
import numpy as np
sharad = np.array([10,15,25,5]) # [5, 10, -20] because 15-10=5, 25-15=10 and 5-25=-20
sharadnew = np.diff(sharad)
print(sharadnew)



[  5  10 -20]


In [ ]:
# finding LCM(Lowest Common Multiple)
# here we will find the LCM of the 2 numbers:

import numpy as np
sharad1 = 4
sharad2 = 6
sharadnew = np.lcm(sharad1, sharad2)
print(sharadnew)
# the answers of the above is 12 because the LCM of both numbers (4*3=12 and 6*2=12) 

# finding the LCM in array:
import numpy as np
sharad = np.array([3,6,9])
sharadnew = np.lcm.reduce(sharad) # the reduce() method will use the ufunc, in this case the lcm() function on each elemtn and it will reduce the array by 1 dimension.
print(sharadnew)


# here we will find the LCM of all of an array where the array contains all integers from 1 to 10.
import numpy as np
sharad = np.arange(1,11)
sharadnew = np.lcm.reduce(sharad)
print(sharadnew)

12
18
2520


In [ ]:
# finding GCD(Gretest common denominator), also known as HCF(Highest Common Factor)

# here wew will find the HCF of the below 2 numbers:
import numpy as np
sharad1 = 6
sharad2 = 9
sharadnew = np.gcd(sharad1, sharad2)
print(sharadnew) # answer will be 3 because that is the highest number  and both umber can be divided by (6/3=2 and 9/3=3)

# finding the GCD in an array
# the reduce() method will use the ufunc, in this case the gcd() function on each elemtn and it will reduce the array by 1 dimension.
import numpy as np
sharad = np.array([20,8,32,16,36])
sharadnew = np.gcd.reduce(sharad)
print(sharadnew)
# it will return 4 because 4 is the highest number of all values that can be divided in between array

3
4


In [ ]:
# what is set? : a set is a collection of unique elements

# for creating the set we use numpy's unique() method to find the unique elements from any array:
# here we will convert the array with repeted elements to a set
import numpy as np
sharad = np.array([1,1,1,2,3,4,5,5,6,7])
sharadnew = np.unique(sharad)
print(sharadnew)

# to find the unique values of 2 1D array, we will use union1d() method
import numpy as np
sharad1 = np.array([1,2,3,4])
sharad2 = np.array([3,4,5,6])
sharadnew = np.union1d(sharad1, sharad2)
print(sharadnew)

# to find the only values tat are present in both array, we will use intersect1d() method.
import numpy as np
sharad1 = np.array([1,2,3,4])
sharad2 = np.array([3,4,5,6])
sharadnew = np.intersect1d(sharad1, sharad2, assume_unique=True)
print(sharadnew)

# to find the only values that are in 1st set and NOT present in the 2nd set: use setfdiff1d()
import numpy as np
sharad1 = np.array([1,2,3,4])
sharad2 = np.array([3,4,5,6])
sharadnew = np.setdiff1d(sharad1, sharad2, assume_unique=True)
print(sharadnew)

# to find the only values that are NOT present in BOTH the sets, use setxor1d() method:
import numpy as np
sharad1 = np.array([1,2,3,4])
sharad2 = np.array([3,4,5,6])
sharadnew = np.setxor1d(sharad1, sharad2, assume_unique=True)
print(sharadnew)








[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
