<a href="https://colab.research.google.com/github/SurajGusain0007/Numpy/blob/main/Numpy_part_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Now we will create a numpy  ndarray object
#the array object in numpy is call ndarry
#array()

In [ ]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#We can also pass a list,tuple or any array like object and it will be converted to ndarray
y=np.array((1,2,3,4,5))
print(y)
print((type(y)))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#Dimensions in array
# A dimensions in Array is one level of array depth(nested array)
#0-D-Scalars ,are the elements in an array,each value in an array is a 0-d array
# Now we will create 0-D array with 42
x=np.array(42)
print(x)
print(type(x))

42
<class 'numpy.ndarray'>


In [ ]:
#1-d array-an array that has 0-d array as its elements is called 1-d array
#or collection of 0-d array also called 1-D array
y=np.array([1,2,3,4,5])
print(y)


[1 2 3 4 5]


In [ ]:
#2-d array
z=np.array([[1,2,3,4,5],[7,8,9,10,11]])
print(z)
print(type(z))

[[ 1  2  3  4  5]
 [ 7  8  9 10 11]]
<class 'numpy.ndarray'>


In [ ]:
# we will create a 3-D array with two 2-D array3-d array or collection of 2-d array
x=np.array([[[1,2,3,4],[5,6,7,8]],
           [[11,12,13,14],[15,16,17,18]]])
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]


In [ ]:
# Check how many dimensions the array have
a=np.array(12)
b=np.array([1,2,3,4])
c=np.array([[1,2,3,4],[5,6,7,8]])
d=np.array([[[1,2,3,4],[5,6,7,8]]
            ,[[11,12,13,14],[15,16,17,18]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#create an array with 5 dim and verify that it has
x=np.array([1,2,3,4,5],ndmin=5)
print(x)
print("No of dimension",x.ndim)

[[[[[1 2 3 4 5]]]]]
No of dimension 5


In [ ]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]],ndmin=5)
print(x)
print("No of dimension",x.ndim)

[[[[[ 1  2  3  4  5]
    [ 6  7  8  9 10]]]]]
No of dimension 5


In [ ]:
# 1- DArray Indexing is the same as accessing an array element
#start with 0
x=np.array([1,2,3,4])
print(x[0])
print(x[2])
print(x[3])

1
3
4


In [ ]:
# We can get the third element and fourth elements fron adding them
x=np.array([1,2,3,4])
print(x[1]+x[2])

5


In [ ]:
# Accessing the 2-D array it is like rows and columns
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#print 2nd element in the ist row
print(x[0][2])
print(x[0,2])

3
3


In [ ]:
x=np.array([[[1,2,3,4],[5,6,7,8]],
           [[11,12,13,14],[15,16,17,18]]])
print(x)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]


In [ ]:
#accessing the 3-d array
#print 6 and 18
print(x[0][1][1])
print(x[1][1][3])

6
18


In [ ]:
# Slicing chapter-3
#slicing array-slicing in python means takeing elements from one given to another given

In [ ]:
#[start:end],[start:end:step]
#now we will slice an element from 1 to 5
x=np.array([1,2,3,4,5,6,7,8,9])
print(x)
print(x[1:5])
print(x[2:7])
print(x[1:6:2])
print(x[4:])
print(x[:5])


[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[3 4 5 6 7]
[2 4 6]
[5 6 7 8 9]
[1 2 3 4 5]


In [ ]:
#negative slicing
print(x[-3:-1])
print(x[:-2])

[7 8]
[1 2 3 4 5 6 7]


In [ ]:
#step:you will step the value to determine the step of the slicing
#return every other value from index 1 to 5
x=np.array([1,23,4,5,6])
print(x[1:4:3])
print(x[::2])

[23]
[1 4 6]


In [ ]:
#Slicing in 2d array
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#slicing in 2d-array
print(x[1,1:3])
print(x[0,1:3])
print(x[1,2:4:2])


[6 7]
[2 3]
[7]


In [ ]:
# another example
print(x[0:2,2])
print(x[0:2,1:4])

[3 7]
[[2 3 4]
 [6 7 8]]


In [ ]:
#slicing in 3 d array
x=np.array([[[1,2,3,4],[5,6,7,8]],
           [[11,12,13,14],[15,16,17,18]]])
print(x)
print(x.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
3


In [ ]:
#slicing in 3 d array
print(x[0,1,1:3])
print(x[1,1,2:4])

[6 7]
[17 18]


In [ ]:
#slicing in 4-d array
x=np.array([[12,13,14,15],[1,2,3,4]],ndmin=4)
print(x)

[[[[12 13 14 15]
   [ 1  2  3  4]]]]


In [ ]:
#slicing
print(x[0,0,1,1:3])

[2 3]


In [ ]:
# Data types ch-4
#data types in numpy
# 1.Int
#2.b for boolen,u for unsigned integer,f for float,complex float, m fortimedelta,datetime
#o for object ,s for string,u for unicode, v for memory

In [ ]:
# checking the data type of numpy array dtype
x=np.array([1,2,3,4,5,8,9,10,9,10])
print(x.dtype)

int64


In [ ]:
y=np.array(['apple','banana',"orange"])
print(y.dtype)

<U6


In [ ]:
# creating an array a defined data type:
x=np.array([1,2,3,4],dtype="S")
print(x)
print(x.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
x=np.array([1,2,3,4],dtype="i4")
print(x)
print(x.dtype)

[1 2 3 4]
int32


In [ ]:
# if a type is given in which the lements cannot be casted then numpy  
# will raise error.What if value cannot be converted

In [ ]:
x=np.array([1,2,'a'],dtype='i')
print(x)

ValueError: ignored

In [ ]:
#converting data type in existing array-()
x=np.array([1.1,2.2,3.4])
y=x.astype("i")
print(x)
print(x.dtype)
print(y)
print(y.dtype)

[1.1 2.2 3.4]
float64
[1 2 3]
int32


In [ ]:
#Numpy array copy and view
# We will make an cpy,change in original array and display both


In [ ]:
x=np.array([1,2,3,4,5])
x1=x.copy()
x[0]=42
print(x)
print(x1)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# now we will make a view,display both
y=np.array([1,2,3,4,5])
y1=y.view()
y[0]=34
print(y)
print(y1)

[34  2  3  4  5]
[34  2  3  4  5]


In [ ]:
# Shape of an array--The no. of element in each dimension
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
print(x.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
# 2,4( which means the array jhas 2 dimension and it has 4 )

In [ ]:
#now we will create 5-D array us ndmin
y=np.array([1,2,3,4],ndmin=5)
print(y)
print(y.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


In [ ]:
x=np.array([[12,13,14,15],[1,2,3,4]],ndmin=4)
print(x)
print(x.shape)

[[[[12 13 14 15]
   [ 1  2  3  4]]]]
(1, 1, 2, 4)


In [ ]:
#Reshaing array-means changing the shape of an array,like adding or removing the elements
#reshaping from 1-D to 2-D array
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=x.reshape(4,3)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# reshaping from 1- D to    3-d
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=x.reshape(3,2,2)
print(y)
print(y[0,1,0:])
print(y[1,0,0:])

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[3 4]
[5 6]


In [ ]:
#unknown dimension:you are only allowed to have one unknwon dimension pass-1
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=y.reshape(3,4,-1)
print(y)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


In [ ]:
# flatteing the array by converting multidimnesional array in 1-D
x=np.array([[1,2,3],[4,5,6]])
y=x.reshape(-1)
print(y)

[1 2 3 4 5 6]


In [ ]:
# There are alot of functions for changing the shape of ana rray in numpy like flatten.ravel also rearranging the element rot90,flip,fliplr,flipud,they all are
# actually comes under advanced numpy

In [ ]:
#Array Iterating-means going through the element one by one step by step.like for loop

#iterate the element of 1-D 
x=np.array([1,2,3,4])
for i in x:
  print(i)

1
2
3
4


In [ ]:
x=np.array([[1,2,3,4],[5,6,7,8]])
for i in x:
  print(i)

[1 2 3 4]
[5 6 7 8]


In [ ]:
#iterate on each scalar element of the 2-d 
x=np.array([[1,2,3,4],[5,6,7,8]])
for i in x:
  for a in i:
    print(a)

1
2
3
4
5
6
7
8


In [ ]:
#Iterate 3-D
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for i in x:
  for a in i:
    for b in a:
      print(b)

1
2
3
4
5
6
7
8
9


In [ ]:
#Iterate arrays using the nditer() function
# Now we will iterate on each scalar element

x=np.array([[[1,2],[4,5],[6,7],[8,9]]])
for i in np.nditer(x):
  print(i)

1
2
4
5
6
7
8
9


In [ ]:
#Now we will iterate with different step size
x=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(x[:,::2]):
  print(i)

1
3
5
7


In [ ]:
#Joining Array
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate((x,y))
print(z)

[1 2 3 4 5 6]


In [ ]:
#Joining of 2-d arrays with rows(axis=1)
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[8,9]])
z=np.concatenate((x,y),axis=1)
print(z)

[[1 2 6 7]
 [4 5 8 9]]


In [ ]:
#Joining array using the stack function:
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[8,9]])
z=np.stack((x,y),axis=1)
print(z)

[[[1 2]
  [6 7]]

 [[4 5]
  [8 9]]]


In [ ]:
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[8,9]])
z=np.hstack((x,y))
print(z)

[[1 2 6 7]
 [4 5 8 9]]


In [ ]:
x=np.array([[1,2],[4,5]])
y=np.array([[6,7],[8,9]])
z=np.vstack((x,y))
print(z)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
# Random Numbers-something that cannot be predicted logically
#Now we will generate a random number

from numpy import random
x=random.randint(100)
print(x)


46


In [ ]:
# you can also generate float() via rand() from 0 to 1
from numpy import random
x=random.rand()
print(x)


0.11618051728002499


In [ ]:
from numpy import random
x=random.rand(100)
print(x)


In [ ]:
#You can also generate random array.
x=random.randint(100,size=(5))
print(x)

[60  4 76 49  0]


In [ ]:
#You can also generate a 2-d array with 3 rows each rows containing 5 random int from o0 to 1000
x=random.randint(100,size=(3,5))
print(x)

[[30 93 33 24 60]
 [51 13 25 96 50]
 [46 11  5 81 66]]


In [ ]:
x=random.rand(5)
print(x)